name: 🐲 Electronics Incident Reporting
description: Create a report to capture details to help RCA
title: "[Electronics Incident Reporting]"
assignees: BartGarciaNathan
body:
  - type: markdown
    attributes:
      value: |
        ## Setup
        
  - type: textarea
    attributes:
      label: ✏️ Which PCB had a problem?
      description: (PCB name + version)
    validations:
      required: true

  - type: textarea
    attributes:
      label: 🔢 What is the PCB individual ID number?
      description: Printed on PCB label
    validations:
      required: false

  - type: textarea
    attributes:
      label: ❓ What is the setup, what is the PCB connected to?
      description: What power (voltage+current if using a power supply) is supplied to the PCB?
    validations:
      required: false

  - type: textarea
    attributes:
      label: 🔢 What firmware is the PCB running?
      description: Version details

  - type: markdown
    attributes:
      value: |
        ## Issue

  - type: textarea
    attributes:
      label: ✏ What is the issue being reported?
      description: A clear and concise description of what you expected to happen.
    validations:
      required: false

  - type: textarea
    attributes:
      label: 👀 Describe the issue
      description: What symptoms or behaviours were seen? Smoke/Noise/Excessive heat? 
    validations:
      required: false

  - type: textarea
    attributes:
      label: 💡 Do you have any supposition of what the issue /source of the problem is?
      description: Add details below
    validations:
      required: false

  - type: textarea
    attributes:
      label: ➿ Has anything else been testing with this PCB since the issue happened?
      description:  What has been tested and what where the outcomes?
    validations:
      required: false

  - type: textarea
    attributes:
      label: 💭 Additional context
      description: Add any other context about the problem here.
